services:
  - type: web
    name: free-vouchers-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: MAIN_CHANNEL_ID
        sync: false
      - key: NOTIFY_CHANNEL_ID
        sync: false
      - key: VERIFY_URL
        sync: false
